#!/usr/bin/env bash

BUCKET_NAME="$1"

echo "Deleting all files from bucket $BUCKET_NAME" >&2

aws s3 --recursive ls "s3://$BUCKET_NAME" \
    | awk '{print $NF}' \
    | xargs -n 1 -P 100 -I@ aws s3 rm "s3://$BUCKET_NAME/@"

echo "Deleting bucket $BUCKET_NAME" >&2
aws s3api delete-bucket --bucket "$BUCKET_NAME"
