#!/bin/sh
# shellcheck disable=SC2046

NOTIFICATION_MESSAGE='Battery low'

notify() {
    notify-send.sh -h string:x-dunst-stack-tag:battery-status -p "$@"
}

clear_notifications() {
    pkill dunst
}

darwin_plugged() {
    if [ "$(pmset -g batt | head -1)" = "Now drawing from 'AC Power'" ]
    then echo yes
    else echo no
    fi
}

linux_plugged() {
    if upower -i /org/freedesktop/UPower/devices/line_power_ADP1 | grep 'online:.*yes' >/dev/null
    then echo yes
    else echo no
    fi
}

prev_color="$1"
next_color="$2"
sep="$3"

case $(uname -a | awk '{print $1}') in
    Darwin)
        plugged=$(darwin_plugged)
        charge=$(pmset -g batt \
                | awk '/-InternalBattery-/ {sub(/%;/, "", $3); print $3}')
        ;;
    Linux)
        plugged=$(linux_plugged)
        charge=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 \
                | awk '/percentage/{sub(/%/, "", $2); printf "%i", $2}')
        ;;
esac

if [ "$plugged" = 'yes' ]
then
    printf "#[fg=%s]%s" "${next_color}" "${sep}"
    clear_notifications
    exit
fi

case "$charge" in
    [0-9] )
        bg=colour196
        notify "$NOTIFICATION_MESSAGE" "$charge%" \
            --icon='battery-caution' \
            --urgency critical \
            --expire-time=60000
    ;;
    1[0-9]) bg=colour202 ;;
    2[0-9]) bg=colour214 ;;
    3[0-9]) bg=colour220 ;;
    4[0-9]) bg=colour45  ;;
    5[0-9]) bg=colour63  ;;
    6[0-9]) bg=colour20; fg=white ;;
    7[0-9]) bg=colour25; fg=white ;;
    8[0-9]) bg=colour35 ;;
    9[0-9]) bg=colour85 ;;
    100)    bg=$next_color;;
esac

fg=${fg:-black}

printf '#[fg=%s,bg=%s]%s' "$bg" "$prev_color" "$sep"	# left separator
printf '#[fg=%s,bg=%s]%s%%' "$fg" "$bg" "$charge"	# percentage
printf '#[fg=%s,bg=%s]%s' "$next_color" "$bg" "$sep"	# right separator
