#!/usr/bin/env sh

prev_color="$1"
full_color="$2"
sep="$3"
next_color="$4"

case $(uname -a | awk '{print $1}') in
    Darwin)
        [ "$(pmset -g batt)" = "Now drawing from 'AC Power'" ] && { echo "#[fg=${full_color}]${sep}"; exit; }
        charge=$(pmset -g batt | awk '/-InternalBattery-/ {sub(/%;/, "", $3); print $3}')
        ;;
    Linux)
        charge=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk '/percentage/{sub(/%/, "", $2); print $2}')
        ;;
esac

case "$charge" in
    [0-9] ) bg=colour196  ;;
    1[0-9]) bg=colour202  ;;
    2[0-9]) bg=colour214; fg=white;;
    3[0-9]) bg=colour220; fg=white;;
    4[0-9]) bg=colour45;  fg=white;;
    5[0-9]) bg=colour63;  fg=white;;
    6[0-9]) bg=colour20;  fg=white;;
    7[0-9]) bg=colour25;  fg=white;;
    8[0-9]) bg=colour35   ;;
    9[0-9]) bg=colour85   ;;
    100)    bg=$full_color;;
esac

fg=${fg:-black}
echo "#[fg=$bg,bg=$prev_color]$sep#[fg=$fg,bg=$bg]$charge%#[fg=$next_color,bg=$bg]$sep"
