#!/usr/bin/env sh

prev_color="$1"
next_color="$2"

output=''
charge=$(pmset -g batt | awk '/-InternalBattery-/ {sub(/%;/, "", $2); print $2}')
status=$(pmset -g batt | awk '/-InternalBattery-/ {sub(/;/, "", $3); print $3}')

case "$charge" in
  [0-9])
    bg=colour196;;
  1[0-9])
    bg=colour202;;
  2[0-9])
    bg=colour214;;
  3[0-9])
    bg=colour220;;
  4[0-9])
    bg=colour45;;
  5[0-9])
    bg=colour63;;
  6[0-9])
    fg=white
    bg=colour20;;
  7[0-9])
    fg=white
    bg=colour25;;
  8[0-9])
    bg=colour35;;
  9[0-9])
    bg=colour85;;
  100)
    bg=$next_color;;
esac

fg=${fg:-black}

case "$status" in
  "charging")
    output="$charge\xe2\x9a\xa1\xef\xb8\x8f ";;
  "charged")
    output='\xe2\x9c\xa8 ';;
  *)
    output="$charge%";;
esac

echo "#[fg=$bg,bg=$prev_color]#[fg=$fg,bg=$bg]$output#[fg=$next_color,bg=$bg]"
