#!/usr/bin/env bash

prev_color="$1"
next_color="$2"
sep="$3"

NOTIFICATION_MESSAGE='Battery low'

function darwin_plugged() {
    if [ "$(pmset -g batt)" = "Now drawing from 'AC Power'" ]
    then echo yes
    else echo no
    fi
}
function linux_plugged() {
    line_power=$(upower -i /org/freedesktop/UPower/devices/line_power_ADP1)
    if grep 'online:.*yes' <<< "$line_power" >/dev/null
    then echo yes
    else echo no
    fi
}

case $(uname -a | awk '{print $1}') in
    Darwin)
        plugged=$(darwin_plugged)
        charge=$(pmset -g batt \
                | awk '/-InternalBattery-/ {sub(/%;/, "", $3); print $3}')
        ;;
    Linux)
        plugged=$(linux_plugged)
        charge=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 \
                | awk '/percentage/{sub(/%/, "", $2); print $2}')
        ;;
esac

if [ "$plugged" = 'yes' ]
then
    printf "#[fg=${next_color}]${sep}"
    exit
fi

case "$charge" in
    [0-9] )
        bg=colour196
        notify-send "$NOTIFICATION_MESSAGE" "$charge%" -u critical
    ;;
    1[0-9])
        bg=colour202
        notify-send "$NOTIFICATION_MESSAGE" "$charge%"
    ;;
    2[0-9]) bg=colour214; fg=black;;
    3[0-9]) bg=colour220; fg=black;;
    4[0-9]) bg=colour45;  fg=black;;
    5[0-9]) bg=colour63;  fg=black;;
    6[0-9]) bg=colour20;  fg=white;;
    7[0-9]) bg=colour25;  fg=white;;
    8[0-9]) bg=colour35   ;;
    9[0-9]) bg=colour85   ;;
    100)    bg=$next_color;;
esac

fg=${fg:-black}

printf '#[fg=%s,bg=%s]%s' $bg $prev_color $sep	# left separator
printf '#[fg=%s,bg=%s]%s%%' $fg $bg $charge	# percentage
printf '#[fg=%s,bg=%s]%s' $next_color $bg $sep	# right separator
