#!/usr/bin/env bash
for directory in defaults files handlers meta tasks templates vars; do
  mkdir -p playbooks/roles/$1/$directory
done

[ ! -e playbooks/roles/$1/meta/main.yml ] && echo "---
galaxy_info:
  author: Brandon Schlueter
  description: A description of the $1 role
  company: Refinery29
  license: MIT
  min_ansible_version: 1.4
  categories: []
  platforms:
  - name: Ubuntu
    versions:
    - all
dependencies: []
" > playbooks/roles/$1/meta/main.yml \
&& echo Initialized meta/main.yml file for $1 \
|| echo meta/main.yml already exists, desisting

for directory in meta tasks; do
  touch playbooks/roles/$1/$directory/main.yml
done

