#!/usr/bin/env bash
# Usage: git-recent-refs [N|pattern]

# Build array of recent branches
mapfile -t all_recent_branches < <(
    git for-each-ref --sort=-committerdate refs | awk '
        /refs\/.*(HEAD|master)$/{next};
        {
            gsub("refs/(remotes/[^/]+|tags|heads)/", "");
            if (!a[$3]++) print $3
        }'
)

# Decide how to filter
if [[ -z "$1" || "$1" =~ ^[0-9]+$ ]]; then
    limit=${1:-10}
    select_branches=("${all_recent_branches[@]:0:limit}")
else
    select_branches=()
    for b in "${all_recent_branches[@]}"; do
        if [[ "$b" =~ $1 ]]; then
            select_branches+=("$b")
        fi
    done
fi

# Handle no matches
if ((${#select_branches[@]} == 0)); then
    echo "No matching branches found"
    exit 1
fi

# Selection menu
select branch in "${select_branches[@]}"; do
    if [[ -n "$branch" ]]; then
        git checkout "$branch"
        break
    fi
done
