#!/usr/bin/env bash
# Usage: git-recent-refs [N]
#     where N is the number of recent branches you want to be able to choose from, defaulting to 10 if not provided

# bash is required for select
all_recent_branches=$(git for-each-ref --sort=-committerdate refs | awk '
    /refs\/.*(HEAD|master)$/{next};
    {
        gsub("refs/(remotes/[^/]+|tags|heads)/", "");
        if (!a[$3]++) print $3
    }')

if (($1)) || [[ -z "$1" ]]; then
    select_branches=$(echo "$all_recent_branches" | head -n "${1:-10}")
else
    select_branches=$(echo "$all_recent_branches" | grep -i "$1")
fi

select branch in $select_branches
do
    git checkout "$branch"
    exit
done
