#!/usr/bin/env bash

((DEBUG)) && set -ex

premature_exit () {
    exit_code="$?"
    if [ ! "$exit_code" == 0 ]
    then
        notifier 'Unable to manage media' 'dialog-error'
        exit "$exit_code"
    fi
}

trap premature_exit EXIT

NOTIFY_ICON_THEME='Enlightenment-X'
NOTIFY_ICON_SIZE='128'
NUMBER_RE='^[0-9]+$'

export NOTIFY_ICON_THEME NOTIFY_ICON_SIZE

sink_index="$(pacmd list-sinks | awk '/\*/{print $3}')"

function mute-state {
    pacmd list-sinks \
        | awk '/\*\ /{t=1};/^\t*muted:/{if (t==1) print $2; t=0}'
}

function volume {
    pacmd list-sinks \
        | awk '/\*\ /{t=1};/^\t*volume:/{if (t==1) print $5; t=0}'
}

if [ -z "$1" ]
then
    notifier "$(volume)"
    echo "$(volume)"
    exit
fi

case "$1" in
    (previous)
        playerctl previous
        notifier 'previous'
    ;;
    (next)
        playerctl next
        notifier 'next'
    ;;
    (play-pause)
        playerctl play-pause
        notifier 'play-pause'
    ;;
    (toggle-mute)
        case "$(mute-state)" in
            (yes)
                pacmd set-sink-mute "${sink_index}" 0
                notifier 'unmuted' '' 'audio-volume'
            ;;
            (no)
                pacmd set-sink-mute "${sink_index}" 1
                notifier 'muted' '' 'audio-volume-muted'
            ;;
        esac
        ;;
    (+)
        shift

        if [[ $1 =~ $NUMBER_RE ]]
        then
            increment="$1"
        else
            increment=5
        fi
        current_volume="$(volume)"
        "$0" "$((${current_volume//%} + increment))"
        ;;
    (-)
        shift
        if [[ $1 =~ $NUMBER_RE ]]
        then
            increment="$1"
        else
            increment=5
        fi
        current_volume="$(volume)"
        "$0" "$((${current_volume//%} - increment))"
        ;;
    (*)
        pacmd set-sink-volume "${sink_index}" $(($1 * 655))
        case "$(volume)" in
            (100%);&
            (9[0-9]%)
                icon='audio-volume-high'
            ;;
            ([3-8][0-9]%)
                icon='audio-volume-medium'
            ;;
            ([1-2][0-9]%);&
            ([1-9]%)
                icon='audio-volume-low'
            ;;
            (0%)
                icon='audio-volume-muted'
            ;;
        esac
        notifier "$(volume)" '' "${icon}"
        if [ "$(mute-state)" == yes ]
        then
            sleep .3
            notifier 'muted' '' "${audio-volume-muted}"
        fi
        ;;
esac
