#!/usr/bin/env zsh

set -e
((DEBUG)) && set -x


zshexit () {
    (($?)) && notify 'Unable to manage media' 'dialog-error'
}

current-mute-state () {
    pacmd list-sinks | awk '/\* /{t=1};/^\t*muted:/{if (t==1) print $2; t=0}'
}

volume () {
    pacmd list-sinks | awk '/\* /{t=1};/^\t*volume:/{if (t==1) print $5; t=0}'
}

notify () {
    notify-send.sh -h string:x-dunst-stack-tag:mediac -p "$@"
}

notify_volume () {
    local volume
    volume="$(volume)"
    case "$(current-mute-state)" in
        (no)
            case "$volume" in
                ([3-8][0-9]%)                   level='medium' ;;
                ([0-9][0-9][0-9]%);& (9[0-9]%)  level='high' ;;
                ([1-2][0-9]%);& ([1-9]%);& (0%) level='low' ;;
            esac

            notify "$volume" --icon="audio-volume-$level" --expire-time=600 ;;
        (yes) notify 'muted' --icon='audio-volume-muted' --expire-time=600 ;;
    esac
}

set-volume () {
    case "$1" in
        (+*) target_volume="$(( ${$(volume)%%%} + ${${1/+}:-5} ))" ;;
        (-*) target_volume="$(( ${$(volume)%%%} - ${${1/-}:-5} ))" ;;
        (*) target_volume="${1:-${$(volume)%%%}}" ;;
    esac
    pacmd set-sink-volume "${sink_index}" $((target_volume * 655))
    notify_volume
}

play-pause () {
    case "$(playerctl status)" in
        (Playing)
            playerctl pause
            notify --icon media-playback-pause-symbolic \
                "Pause"
            ;;
        (Paused)
            playerctl play
            notify --icon media-playback-start-symbolic \
                "Play"
            ;;
    esac
}

next-or-previous () {
    case "$(playerctl status)" in
        (Playing)
            playerctl pause
            notify --icon 'media-playback-pause-symbolic' \
                "Pause"
            ;;
        (Paused)
            playerctl play
            notify --icon 'media-playback-start-symbolic' \
                "Play"
            ;;
    esac
}

next () {
    playerctl 'next'
    notify --icon 'media-skip-forward' 'next'
}

previous () {
    playerctl 'previous'
    notify --icon 'media-skip-backward' 'previous'
}

toggle-mute () {
        if [ "$arg2" = 'yes' ] || [ "$arg2" = 'no' ]
        then
            mute_state="$arg2"
        else
            mute_state="${${$(current-mute-state)/yes/0}/no/1}"
        fi
        pacmd set-sink-mute "${sink_index}" "$mute_state"
        notify_volume
}

usage () {
    cat <<EOF >&2
mediac [next|previous|play-pause|toggle-mute [yes|no]] | [<volume>|[+|-]<delta>]
EOF
}

sink_index="$(pacmd list-sinks | awk '/\*/{print $3}')"
arg="$1"
arg2="$2"
case "$arg" in
    (next|previous|play-pause|toggle-mute) "$arg" ;;
    (*)
        if [ "$arg" = 0 ] || [ $((arg)) -ne 0 ]
        then
            set-volume "$arg"
        else
            usage
        fi ;;
esac
