#!/usr/bin/env bash
/usr/bin/env osascript << EOS
tell application "iTerm"
  activate

  -- talk to the first terminal
  tell the first terminal

    -- launch a default shell in a new tab in the same terminal
    launch session "Default Session"

    tell the last session

      -- write some text
      write text "$@"

    end tell

  end tell

end tell
EOS
