#!/usr/bin/env bash

function _notification {
    summary="$1"
    body="$2"
    icon="$3"
    theme="${4:-}"
    size="${5:-}"
    hint='string:x-canonical-private-synchronous:volume'

    if [ -z "$theme" ] || [ -z "$size" ]
    then
        notification_icon="$icon"
    else
        notification_icon="/usr/share/icons/${theme}/status/${size}/${icon}.png"
    fi

    notify-send "$summary" "$body" --icon="$notification_icon" --hint="$hint"
}

function main {
    summary="$1"
    body="$2"
    icon="$3"
    theme="${NOTIFY_ICON_THEME:-}"
    size="${NOTIFY_ICON_SIZE:-}"
    _notification "$summary" "$body" "$icon" "$theme" "$size"
}

main "$@"
