#!/usr/bin/env bash

#
# Usage:
#

set -e

function docstring {
    sed -n "s/\$0/$(basename "$0")/; s/^# //p" "$0"
}

function bad_command {
    echo -e "\033[0;31mNo such command '$*'\033[0m" >&2
    docstring
    exit 1
}

function security_group_ports {
#   $0 security group ports
    local id
    for id in $(openstack security group list -f json | jq -r '.[] | .ID')
    do
        openstack security group show -f json "$id" \
          | jq -r .project_id \
          | xargs openstack project show -f json \
          | jq '.description'
        echo "Security Group ID: $id"
        openstack security group rule list -f json \
          | jq -r "$(cat <<EOF
.
| map(select(."Security Group" | contains("$id")))
| map(select(."IP Protocol" != null))
| .[]
| ."IP Protocol" + " " + ."IP Range" + " " + ."Port Range"
EOF
)"
    done
}

function current_image_starting_with {
#   $0 current image starting with [<startswith=provisioning>]
    local startswith
    startswith="$*"
    startswith="${startswith:-provisioning}"
    openstack image list --long --format json \
      | jq -r "$(cat <<EOF
.
| map(select(.Name | startswith("$startswith")))
| map(select(.Tags | contains("current")))
| first
EOF
)"
}

function remote_vnc {
#   $0 remote vnc <jump host> [<remote_controller=control-01.nyc.rf29.net> [<local_port=6080>]
    local jump remote_controller local_port
    jump="${1:-r29-mm}"
    remote_controller="${2:-control-01.nyc.rf29.net}"
    local_port="${3:-6080}"
    # shellcheck disable=SC2029
    ssh -L "$local_port:$remote_controller:6080" "$jump" &
}

function main {
    declare -a query
    query=( "$@" )
    case "${query[*]}" in
        (security\ group\ ports) security_group_ports;;
        (current\ image\ starting\ with*) current_image_starting_with "${query[@]:4}";;
        (remote_vnc*) remote_vnc "${query[@]:2}";;
        ('') docstring;;
        (*) bad_command "${query[*]}";;
    esac
}

main "$@"
