#!/usr/bin/expect -f
set password [lindex $argv 0]
set inventory [lindex $argv 1]
set playbook [lindex $argv 2]
spawn ansible-playbook --ask-sudo-pass -i $inventory $playbook
expect "SUDO password:"
send "$password\n"
interact
