#!/bin/sh

lockfile="$TMPDIR/dont-lock-screen"
if [ ! -f "$lockfile" ]
then
    notifier 'Locking screen in 30 seconds'
    sleep 30
    if [ ! -f "$lockfile" ]
    then
        echo 'Locking with slock' >&2
        exec slock
    fi
fi
echo 'Not locking' >&2
