#!/usr/bin/env bash

tmux_mouse_file="$HOME/.session/tmux_mouse"
tmux_mouse_state="$(cat $tmux_mouse_file 2>/dev/null)"
if [ "${tmux_mouse_state:-ON}" = ON ]
then
    tmux set mouse off
    notifier "Tmux mouse off"
    echo 'OFF' > "$tmux_mouse_file"
else
    tmux set mouse on
    notifier "Tmux mouse on"
    echo 'ON' > "$tmux_mouse_file"
fi
