#!/usr/bin/env bash

source notifier

device="${1:-bcm5974}"
if xinput list "${device}" | grep "This device is disabled" > /dev/null
then
    xinput --enable "${device}"
    notification 'trackpad enabled'
else
    xinput --disable "${device}"
    notification 'trackpad disabled'
fi
