#!/usr/bin/env python

import yaml
import subprocess


for script in yaml.load(open(".travis.yml"))["script"]:
    exit_status = subprocess.call(script, shell=True)
    if exit_status != 0:
        exit(exit_status)
