#!/usr/bin/env python

import subprocess
import sys

import yaml

def notice(*msg):
    print '\033[93m' + ' '.join(msg) + '\033[0m'

try:
    for script in yaml.load(open(".travis.yml"))["script"]:
        notice("running test script:\n\n{}".format(script))
        exit_status = subprocess.call(script, shell=True, stderr=open('/dev/null'))
        if exit_status != 0:
            exit(exit_status)
except KeyboardInterrupt:
  sys.exit()
