#!/bin/sh
name_string="${1:-Corsair_VOID_Wireless}"
headset_index=$(pacmd list-sinks | awk -v search_str="name:.*$name_string" '$0 ~ search_str {print a; exit}{a=$0}' | sed 's/.*index:\ //')
pacmd set-default-sink "$headset_index" || echo Failed to set default >&2
for i in $(pacmd list-sink-inputs | sed -n 's/.*index:\ //p')
do
   pacmd move-sink-input "$i" "$headset_index" || echo Failed to move "$i" >&2
done
