#!/usr/bin/env bash

sink_index=$(pacmd list-sinks | grep '*' | awk '/\\*/{ print $3}')

if [[ -z "$1" ]]
then
    pacmd list-sinks | awk '/\*\ /{t=1};/^\t*volume:/{if (t==1) print $5}'
else
    case "$1" in
        (--toggle-mute)
            pactl set-sink-mute "${sink_index}" toggle
            ;;
        (--mute-state)
            mute_state=$( \
                pacmd list-sinks \
                | awk '/\*\ /{t=1};/^\t*muted:/{if (t==1) print $2}'
            )
            case "$mute_state" in
                (yes) echo muted;;
                (no) echo unmuted;;
            esac
            ;;
        (*)
            pactl set-sink-volume "${sink_index}" "$1"
            ;;
    esac
fi
