#!/usr/bin/env bash

sink_index=$(pacmd list-sinks | grep '*' | awk '/\\*/{ print $3}')

if [[ -z "$1" ]]
then
    pactl list sinks | grep '^[[:space:]]Volume:' | \
        head -n $(( sink_index + 1 )) | tail -n 1 | \
        sed -e 's,.* \([0-9][0-9]*%\).*,\1,'
else
    case "$1" in
        (--toggle-mute)
            pactl set-sink-mute "${sink_index}" toggle
            ;;
        (--mute-state)
            mute_state=$(pacmd list-sinks \
              | grep '^[[:space:]]muted:' \
              | head -n $(( sink_index + 1 )) \
              | tail -n 1 \
              | awk '{print $2}')
            case "$mute_state" in
                (yes) echo muted;;
                (no) echo unmuted;;
            esac
            ;;
        (*)
            pactl set-sink-volume "${sink_index}" "$1"
            ;;
    esac
fi
