#!/usr/bin/env bash

control_c() {
    kill $$
    cd -
    exit
}

trap control_c SIGINT

if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) ]]; then
  cd $(git rev-parse --show-toplevel)
fi

while sleep 1; do
  find playbooks -maxdepth 1 -name "*.yml" | \
  entr bash -c '
  function pass() {
    echo -e "\033[92m$@\033[0m";
  }

  function pass_and_say() {
    echo -e "\033[92m$@\033[0m";
    say $@
  }

  function warn_and_say() {
    echo -e "\033[91m$@\033[0m";
    say $@
  }

  function notice() {
    echo -e "\033[93m$@\033[0m";
  }


  traviscitest 2> /tmp/traviscitest_out
  traviscitest_exit_code=${PIPESTATUS[0]}

  if [[ -f ".traviscitest_result" ]]
  then
    previous_exit_code=$(cat .traviscitest_result)
  else
    previous_exit_code=0
  fi

  if [[ "$traviscitest_exit_code" == 0 ]]
  then
    if [[ "$previous_exit_code" != 0 ]]
    then
      pass_and_say now passing travistests check
    else
      pass passing travistests check
    fi
  else
    if [[ "$previous_exit_code" == 0 ]]
    then
      warn_and_say failing travistests check
    else
      warn_and_say still failing travistests check
    fi
  fi

  cat /tmp/traviscitest_out
  echo $traviscitest_exit_code > .traviscitest_result
  rm /tmp/travistest_out 2> /dev/null'
done

