#!/usr/bin/env python

import sys
import tempfile

import yaml

def clean_yaml(filename: str):
    with open(filename, 'r') as file:
        input = yaml.safe_load(file)


if __name__ == '__main__':
    clean_yaml(sys.argv[1])
